'use strict';
const $=s=>document.querySelector(s);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const math=value=>esc(value).replace(/\^([0-9]+(?:\/[0-9]+)?)/g,'<sup>$1</sup>');
const degree=value=>{const [a,b=1]=String(value).split('/');return Number(a)/Number(b)};
const power=(v,n)=>String(n)==='0'?'1':String(n)==='1'?v:`${v}<sup>${esc(n)}</sup>`;
let catalog=[],record=null,selected='',tab='indices',datasetId='',form='macdonald',cutoff=null,requestId=0;
const staticSite=document.querySelector('meta[name="results-mode"]')?.content==='static';
const tabs=[['indices','Indices'],['flavor','Flavor characters'],['scheme','KLS scheme'],['evidence','Evidence & sources']];
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
async function api(url){if(staticSite){url=url==='/api/catalog'?'./data/catalog.json':'./data/theories/'+url.slice('/api/theories/'.length)+'.json'}const response=await fetch(url,{signal:AbortSignal.timeout(30000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load results.');return data}
function dataset(){return record.datasets.find(d=>d.id===datasetId)||record.datasets[0]}
function polynomial(terms,v='T'){const pieces=terms.filter(t=>t.value!=='0').map(t=>{const exp=t.T??t.q;return exp==='0'?esc(t.value):`${t.value==='1'?'':esc(t.value)+' '}${power(v,exp)}`});return pieces.join(' + ').replace(/\+ -/g,'− ')||'0'}
function filterList(){const query=$('#search').value.toLowerCase().replace(/\s/g,'');const family=$('#family').value,status=$('#status').value;const rows=catalog.filter(r=>(!family||r.lie_type===family)&&(!status||r.status===status)&&(!$('#unhiggsed').checked||r.orbit==='0')&&`${r.title} ${r.lie_type} p${r.p} ${r.orbit}`.toLowerCase().replace(/\s/g,'').includes(query));$('#count').textContent=`${rows.length} / ${catalog.length} theories`;
$('#theories').innerHTML=rows.map(r=>`<a class="theory-link ${r.id===selected?'active':''}" href="#${encodeURIComponent(r.id)}" ${r.id===selected?'aria-current="page"':''}><div class="name">D<sub>${r.p}</sub>(${esc(r.group)})</div>${r.orbit!=='0'?`<div class="orbit">Y = ${esc(r.orbit)}</div>`:''}<div class="meta"><span><i class="dot ${esc(r.status)}"></i>${esc(r.status_label)}</span><span>q ≤ ${esc(r.max_q)}</span></div></a>`).join('')||'<div class="no-results">No matching theories.</div>'}
async function loadCatalog(){const data=await api('/api/catalog');catalog=data.theories;$('#revision').textContent=staticSite?`Snapshot ${data.generated_at_utc.slice(0,10)} · ${data.theories.length} theories`:`${data.source_count} sources · ${data.revision}`;const prior=$('#family').value;$('#family').innerHTML='<option value="">All types</option>'+[...new Set(catalog.map(r=>r.lie_type))].sort().map(f=>`<option>${esc(f)}</option>`).join('');$('#family').value=prior;filterList();return data}
async function selectTheory(id){const serial=++requestId;selected=id;filterList();$('#main').setAttribute('aria-busy','true');try{const data=await api(`/api/theories/${encodeURIComponent(id)}`);if(serial!==requestId)return;record=data;datasetId=(data.datasets.find(d=>d.id==='accepted')||data.datasets[0]).id;form=dataset().macdonald?'macdonald':'schur';cutoff=null;render();}catch(e){if(serial===requestId)$('#main').innerHTML=`<div class="notice error">${esc(e.message)}</div>`}finally{if(serial===requestId)$('#main').removeAttribute('aria-busy')}}
function datasetControls(){const d=dataset();return `<label class="small" for="dataset">Select computation</label><select id="dataset" class="dataset">${record.datasets.map(x=>`<option value="${esc(x.id)}" ${x.id===d.id?'selected':''}>${esc(x.label)} · q ≤ ${esc(x.cutoff)}</option>`).join('')}</select><div class="small">${esc(d.arithmetic||'See source')}</div>`}
function render(){const d=dataset();const forms=record.available_forms.map(f=>({schur:'Schur',macdonald:'Macdonald',hl:'HL',characters:'Characters'}[f]));$('#main').innerHTML=`<div class="eyebrow">${esc(record.lie_type)} / D<sub>p</sub>(G) COLLECTION</div><div class="title-row"><div><h2 class="theory-title">D<sub>${record.p}</sub>(${esc(record.group)})</h2><p class="subtitle">${record.orbit==='0'?'Unhiggsed · Y = 0':`Nilpotent Higgsing · Y = ${esc(record.orbit)}`} &nbsp; <span class="badge ${esc(record.status)}">${esc(record.status_label)}</span></p></div><button id="download">JSON ↓</button></div><div class="stat-grid"><div class="stat"><div class="stat-label">FLAVOR</div><div class="stat-value">${esc(record.flavor.group)}</div></div><div class="stat"><div class="stat-label">PARAMETER</div><div class="stat-value">p = ${record.p}</div></div><div class="stat"><div class="stat-label">STORED CUTOFF</div><div class="stat-value">q ≤ ${esc(record.max_q)}</div></div><div class="stat"><div class="stat-label">AVAILABLE</div><div class="small">${forms.join(' · ')}</div></div></div>${record.obstruction?`<div class="notice error"><strong>HL mismatch in the current KLS filtration</strong><br>${esc(record.obstruction.conclusion)}<br>This candidate is not a completed physical Macdonald index.</div>`:''}<div class="tabs" role="tablist">${tabs.map(([key,label])=>`<button role="tab" aria-selected="${tab===key}" class="tab ${tab===key?'active':''}" data-tab="${key}">${label}</button>`).join('')}</div><section id="panel" role="tabpanel"></section>`;
$('#download').onclick=()=>download(`${record.id}.json`,JSON.stringify(record,null,2),'application/json');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});if(tab==='scheme')renderScheme();else if(tab==='evidence')renderEvidence();else renderIndices();}
function renderIndices(){const d=dataset();const flavored=tab==='flavor';const sourceRows=(d[form]||d.macdonald||d.schur||[]);const options=sourceRows.map(r=>r.q);if(cutoff===null||!options.includes(cutoff))cutoff=options.at(-1)||'0';
$('#panel').innerHTML=datasetControls()+`<div class="panel-head"><h3>${flavored?'Flavor-refined characters':'Index expansions'}</h3><span class="small">From the vacuum to the selected cutoff</span></div><div class="controls"><label for="form">Form</label><select id="form"><option value="macdonald" ${form==='macdonald'?'selected':''}>Macdonald · q,T</option><option value="schur" ${form==='schur'?'selected':''}>Schur · T=1</option><option value="hl" ${form==='hl'?'selected':''}>Hall–Littlewood · diagonal</option></select><label for="cutoff">q ≤</label><select id="cutoff">${options.map(q=>`<option ${q===cutoff?'selected':''}>${esc(q)}</option>`).join('')}</select><button id="copy-series">Copy series</button><button id="tex">TeX ↓</button></div><div class="small">I<sub>M</sub>(q,T;x) = ∑ q<sup>n</sup> C<sub>n</sub>(T;x), &nbsp; I<sub>S</sub>(q;x) = I<sub>M</sub>(q,1;x), &nbsp; I<sub>HL</sub>(t;x) = ∑ t<sup>n</sup> C<sub>n,n</sub>(x). Half-integer degrees are preserved.</div><div id="series-body"></div>`;
$('#dataset').onchange=e=>{datasetId=e.target.value;cutoff=null;form=dataset().macdonald?'macdonald':'schur';render()};$('#form').onchange=e=>{form=e.target.value;cutoff=null;renderIndices()};$('#cutoff').onchange=e=>{cutoff=e.target.value;renderSeries()};$('#copy-series').onclick=async()=>{try{await navigator.clipboard.writeText(exportSeries(false));toast('Copied the complete selected series.')}catch(e){toast('Use the TeX download if copying is unavailable.')}};$('#tex').onclick=()=>download(`${record.id}-${form}${flavored?'-characters':''}.tex`,exportSeries(true),'text/plain');renderSeries();}
function charTerm(term,tex=false){const mult=String(term.multiplicity);const factors=term.irreps.map(i=>{if(i.dynkin.every(x=>Number(x)===0))return '';return tex?`\\chi^{\\mathrm{${i.group}}}_{(${i.dynkin.join(',')})}(x)`:`χ<sub>${esc(i.group)} [${i.dynkin.join(',')}]</sub>(x)`}).filter(Boolean);(term.u1_charges||[]).forEach((charge,i)=>{if(String(charge)!=='0')factors.push(tex?`z_{${i+1}}^{${charge}}`:`z<sub>${i+1}</sub><sup>${esc(charge)}</sup>`)});return (mult==='1'&&factors.length?'':mult+(factors.length?' ':''))+factors.join(tex?' ':' · ')}
function sumCharacters(terms){const merged=new Map();for(const t of terms){const key=JSON.stringify([t.irreps,t.u1_charges]);const prev=merged.get(key);if(prev)prev.multiplicity=String(BigInt(prev.multiplicity)+BigInt(t.multiplicity));else merged.set(key,{...t,multiplicity:String(t.multiplicity)})}return [...merged.values()].filter(t=>t.multiplicity!=='0')}
function selectedCharacterRows(){return (dataset().characters||[]).filter(r=>degree(r.q)<=degree(cutoff)).map(r=>{let cells=r.cells;if(form==='hl')cells=cells.filter(c=>degree(c.T)===degree(r.q));if(form!=='macdonald')cells=[{T:'0',terms:sumCharacters(cells.flatMap(c=>c.terms))}];return {...r,cells}})}
function renderSeries(){const d=dataset(),body=$('#series-body');if(tab==='flavor'){
let html='';if(record.schur_character_formula)html+=`<div class="card"><h3>Flavor-refined Schur · closed formula</h3><div class="formula">${math(record.schur_character_formula)}</div><div class="small">χ denotes a flavor character. PE[f] = exp(∑<sub>k≥1</sub> f(q<sup>k</sup>,x<sup>k</sup>)/k). <a href="${esc(record.schur_character_source.url)}" target="_blank" rel="noreferrer">Kang–Lawrie–Song, Eq. (3.7)</a></div></div>`;
if(d.characters){html+=`<div class="small">χ<sub>G [a₁,…,aᵣ]</sub> uses Dynkin labels. z denotes a U(1) fugacity; distinct representations of equal dimension remain separate.</div><div class="table-wrap"><table><thead><tr><th>q degree</th><th>${esc(form)} character coefficient</th></tr></thead><tbody>${selectedCharacterRows().map(r=>`<tr><td class="degree">${esc(r.q)}</td><td class="character">${r.cells.map(c=>`<div class="character-row"><span class="t">${form==='macdonald'?power('T',c.T):''}</span><span>${c.terms.map(t=>`<span class="char-term">${charTerm(t)}</span>`).join(' + ')||'0'}</span></div>`).join('')||'0'}</td></tr>`).join('')}</tbody></table></div>`;}else{html+='<div class="empty">No complete coefficientwise flavor decomposition is stored for this computation. Representations are not inferred from unrefined dimensions.</div>';if(d.first_null_character_formula||record.first_null_character_formula)html+=`<div class="card"><h3>KLS candidate through the first null · representation-ring formula</h3><div class="formula">${math(d.first_null_character_formula||record.first_null_character_formula)}</div><p class="small">Valid only below the displayed O(q…) order. ${esc(record.notes.find(n=>n.includes('character formula'))||'')}</p></div>`;if(d.ideal_characters)html+=`<details><summary>Stored ideal-image characters (not the full index characters)</summary><pre>${esc(JSON.stringify(d.ideal_characters,null,2))}</pre></details>`;}
body.innerHTML=html;return;}
const rows=d[form];if(!rows){body.innerHTML=`<div class="empty">This dataset has no ${esc(form)} series. Select another dataset or consult the known formula in the flavor tab.</div>`;return;}
const filtered=rows.filter(r=>degree(r.q)<=degree(cutoff));const reference=d[`${form}_target`]||((form==='schur')?d.arc_schur:null);const refMap=new Map((reference||[]).map(r=>[r.q,r.value]));
const summary=form==='macdonald'?filtered.map(r=>({q:r.q,value:polynomial(r.terms)})):filtered;
body.innerHTML=`<details><summary>Expand complete series</summary><div class="formula">${form==='macdonald'?'I<sub>M</sub>(q,T)':form==='schur'?'I<sub>S</sub>(q)':'I<sub>HL</sub>(t)'} = ${summary.map(r=>{const coefficient=form==='macdonald'?r.value:esc(r.value);if(coefficient==='0')return '';return r.q==='0'?coefficient:`${power(form==='hl'?'t':'q',r.q)} (${coefficient})`}).filter(Boolean).join(' + ')}<span class="small"> &nbsp; (degree ≤ ${esc(cutoff)})</span></div></details><div class="table-wrap"><table><thead><tr><th>Degree n</th><th>${form==='macdonald'?'Cₙ(T)':'Coefficient'}</th>${reference?'<th>Reference coefficient</th><th>Comparison</th>':''}</tr></thead><tbody>${filtered.map(r=>`<tr><td class="degree">${esc(r.q)}</td><td class="math">${form==='macdonald'?polynomial(r.terms):esc(r.value)}</td>${reference?`<td class="math">${esc(refMap.get(r.q)??'Not computed')}</td><td class="${r.value===refMap.get(r.q)?'match':'mismatch'}">${r.value===refMap.get(r.q)?'Match':'Mismatch'}</td>`:''}</tr>`).join('')}</tbody></table></div><div class="footer-note">${form==='hl'?'This table is the diagonal of the selected Macdonald candidate. Reference coefficients come from the stored independent Higgs-orbit calculation.':'Coefficients beyond the displayed cutoff are unknown, not zero.'} ${reference&&form==='schur'?'The comparison column uses the stored independent Schur reference or arc series.':''}</div>`;
}
function renderScheme(){const s=dataset().scheme||record.scheme;$('#panel').innerHTML=datasetControls()+`<div class="panel-head"><h3>KLS scheme</h3><span class="small">The scheme and its reduced support are distinct</span></div><div class="formula">${math(s.definition)}</div><div class="card"><h3>Potential · degree ${s.potential_degree}</h3><div class="formula">${s.potential_mathml||esc(s.potential||'Explicit potential: see source')}</div>${s.potential_tex?`<button id="potential-tex">Copy potential TeX</button>`:''}${s.convention?`<p class="small">${esc(s.convention)}</p>`:''}${s.invariants.length?`<div class="table-wrap"><table><thead><tr><th>Invariant</th><th>Degree</th></tr></thead><tbody>${s.invariants.map(i=>`<tr><td>${esc(i.name)}</td><td>${i.degree}</td></tr>`).join('')}</tbody></table></div>`:''}</div>${[['Slodowy slice',s.slice],['Graph equations',s.graph],['Bigrading',s.grading],['Reduced support',typeof s.support==='string'?s.support:JSON.stringify(s.support)],['Scheme structure',s.distinction]].map(([k,v])=>`<div class="kv"><strong>${k}</strong><div>${math(v)}</div></div>`).join('')}${s.filtration_certificate?`<details><summary>Pfaffian filtration · assumptions and exact evidence</summary><pre>${esc(JSON.stringify(s.filtration_certificate,null,2))}</pre></details>`:''}${s.associated_orbits?`<details><summary>Associated orbits by p</summary><pre>${esc(JSON.stringify(s.associated_orbits,null,2))}</pre></details>`:''}${s.special_geometries?`<details><summary>Known special geometries</summary><pre>${esc(JSON.stringify(s.special_geometries,null,2))}</pre></details>`:''}${record.obstruction?`<div class="notice error">${esc(record.obstruction.interpretation)}</div>`:''}<div class="footer-note">Index agreement is not assumed for new D/E candidates. See the evidence tab for the verified scope.</div>`;$('#dataset').onchange=e=>{datasetId=e.target.value;renderScheme()};if(s.potential_tex)$('#potential-tex').onclick=async()=>{try{await navigator.clipboard.writeText(s.potential_tex);toast('Copied potential TeX.')}catch(e){download(`${record.id}-potential.tex`,s.potential_tex,'text/plain')}}}
function sourceLinks(){const links=record.sources.map(source=>{const url=source.startsWith('https://')?source:`./source/${encodeURIComponent(source)}`;return `<a class="source" href="${esc(url)}" target="_blank" rel="noreferrer">↗ ${esc(source)}</a>`}).join('');return (staticSite?`<a class="source" href="./data/theories/${encodeURIComponent(record.id)}.json" target="_blank" rel="noreferrer">↗ Published theory data and verification metadata</a><a class="source" href="./manifest.json" target="_blank" rel="noreferrer">↗ Snapshot manifest and checksums</a>`:'')+links}
function renderEvidence(){const d=dataset();$('#panel').innerHTML=datasetControls()+`<div class="card"><h3>Verification scope</h3><p>Stored cutoff: q ≤ ${esc(d.cutoff)}</p><p>${esc(d.scope||'See the original verification records below.')}</p><div class="notice"><strong>${esc(record.status_label)}</strong><p>${esc(record.status_description)}</p>${record.completion?`<p>Full campaign (exact Macdonald + Schur/HL limits): ${record.completion.complete?'Complete':'Incomplete'} · Required cutoff: ${esc(record.completion.required_cutoff??'jump not yet located')}</p>`:''}<p>Selected computation: ${d.schur_jump_plus_two?'Schur jump + 2 checked':'No separate Schur jump + 2 completion recorded for this computation'}.</p></div>${record.completion?.missing_requirements?.length?`<details><summary>Outstanding campaign requirements</summary><ul>${record.completion.missing_requirements.map(item=>`<li>${esc(item.replaceAll('-',' '))}</li>`).join('')}</ul></details>`:''}<pre>${esc(JSON.stringify(d.checks||{},null,2))}</pre></div>${record.notes.map(n=>`<p class="small">${esc(n)}</p>`).join('')}${record.obstruction?`<details><summary>Model obstruction · assumptions, conclusion, proof</summary><pre>${esc(JSON.stringify(record.obstruction,null,2))}</pre></details>`:''}${d.provenance?`<details><summary>Original verification metadata</summary><pre>${esc(JSON.stringify(d.provenance,null,2))}</pre></details>`:''}<div class="card"><h3>Source data</h3>${sourceLinks()}</div><p class="footer-note">The browser reads stored results. Exact coefficients retain their full precision. ${staticSite?'This is a published snapshot; updates appear after a new deployment.':'Refresh to read the latest cumulative data.'}</p>`;$('#dataset').onchange=e=>{datasetId=e.target.value;renderEvidence()}}
function exportSeries(tex){const d=dataset();let pieces=[];if(tab==='flavor'){if(!d.characters)return `% No coefficientwise character table for ${record.id}.\n${record.schur_character_formula||''}\n${d.first_null_character_formula||record.first_null_character_formula||''}`;pieces=selectedCharacterRows().map(r=>{const cells=r.cells.map(c=>{const chars=c.terms.map(t=>charTerm(t,tex)).join(' + ')||'0';return form==='macdonald'&&c.T!=='0'?`T^{${c.T}} (${chars})`:chars}).join(' + ')||'0';return r.q==='0'?`(${cells})`:`${form==='hl'?'t':'q'}^{${r.q}} (${cells})`})}else{if(!d[form])return `% No ${form} series stored for ${record.id}.`;pieces=d[form].filter(r=>degree(r.q)<=degree(cutoff)).map(r=>{const coefficient=form==='macdonald'?r.terms.map(t=>t.T==='0'?t.value:`${t.value} T^{${t.T}}`).join(' + ')||'0':r.value;return r.q==='0'?`(${coefficient})`:`${form==='hl'?'t':'q'}^{${r.q}} (${coefficient})`})}const expression=pieces.join(' + ');return tex?`% ${record.title}; ${d.label}; includes every stored degree <= ${cutoff}.\n% Finite truncation; no higher coefficients asserted.\n\\[\n${expression}\n\\]\n`:expression+`\n(stored truncation through ${cutoff})`}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
for(const selector of ['#search','#family','#status','#unhiggsed'])$(selector).addEventListener('input',filterList);
$('#refresh').onclick=async()=>{try{await loadCatalog();await selectTheory(selected||catalog[0].id);toast('Reloaded source results.')}catch(e){toast(e.message)}};
window.addEventListener('hashchange',()=>selectTheory(decodeURIComponent(location.hash.slice(1))||catalog[0].id));
(async()=>{try{await loadCatalog();await selectTheory(decodeURIComponent(location.hash.slice(1))||catalog[0].id)}catch(e){$('#main').innerHTML=`<div class="notice error">${esc(e.message)}</div>`}})();
